apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gs-spring-boot-docker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gs-spring-boot-docker
    spec:
      containers:
      - image: acrcontainer222.azurecr.io.azurecr.io/gs-spring-boot-docker:__Build.BuildId__
        name: gs-spring-boot-docker
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: gs-spring-boot-docker
  type: LoadBalancer
